-- Supabase 数据库初始化 SQL
-- 在 Supabase SQL Editor 中执行

-- 创建 posts 表
CREATE TABLE IF NOT EXISTS posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  content TEXT NOT NULL,
  excerpt TEXT,
  cover_image TEXT,
  published BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 启用 RLS
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;

-- 公开读取策略
CREATE POLICY "Public posts are viewable by everyone" 
  ON posts FOR SELECT 
  USING (published = true);

-- 插入示例文章
INSERT INTO posts (title, slug, content, excerpt, published) VALUES
('第一眼选物品，测你的隐藏性格是什么？', 'test-hidden-personality', 
'## 正文\n\n第一眼选物品，测你的隐藏性格是什么？\n\n有时候，我们的潜意识会暴露真实的自己\n不要思考，相信你的第一直觉！\n\n看下面的物品，第一眼你会选择哪个？\n\n---\n\n### 第 1 组\nA. 一本泛黄的旧书 📖\nB. 一把精致的钥匙 🔑\nC. 一朵枯萎的花 🥀\nD. 一个破碎的镜子 🪞\n\n**选好了吗？统计你选最多的字母，看下面的解析！**',
'第一眼选物品，测你的隐藏性格。记忆收藏家、未来探索者、内心守护者、情感治愈师你是哪一种？', true),

('现代软件开发 50 个核心知识点', 'modern-software-dev-50-points',
'## 现代软件开发 50 个核心知识点\n\n1. **版本控制 (Git)** - 代码管理的基础\n2. **代码审查** - 提高代码质量\n3. **持续集成/持续部署 (CI/CD)** - 自动化构建和部署\n...',
'掌握现代软件开发的 50 个核心知识点，提升开发能力', true),

('AI Daily Report - 2026-02-21', 'ai-daily-report-2026-02-21',
'## AI Daily Report - 2026年2月21日\n\n### 今日 AI 热点\n\n1. **Claude 3 发布** - Anthropic 发布最新 Claude 3 系列模型\n2. **GPT-5  rumors** - OpenAI 即将发布 GPT-5\n3. **Google Gemini Ultra 发布** - Google 推出最强模型\n\n### 技术进展\n\n- 多模态能力大幅提升\n- 长上下文窗口成为标配\n- AI 编程能力显著增强',
'2026年2月21日 AI 行业动态日报', true);
